import type { Metadata } from "next";
import { pageSocialMetadata } from "@/lib/siteMetadata";

const description =
  "How AI Policy File handles checker answers, founding-list submissions, analytics, service providers, retention, and privacy rights.";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description,
  alternates: { canonical: "/privacy" },
  ...pageSocialMetadata("Privacy Policy", description, "/privacy"),
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <h1 className="font-display text-3xl font-bold tracking-tight text-slate-900">
        Privacy Policy
      </h1>
      <p className="mt-2 text-sm text-slate-600">Last updated: August 29, 2026</p>
      <div className="mt-6 space-y-4 leading-relaxed text-slate-700">
        <h2 className="font-display text-xl font-semibold text-slate-900">Controller and contact</h2>
        <p>
          Jason Ramirez, the site owner and maintainer, determines why and how this website
          processes the data described below and is the controller for that processing. Contact:
          hello@aipolicyfile.com. No separate data protection officer or European Union
          representative contact has been verified for this site. This public contact does not
          replace any appointment that applicable law may require.
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">The checker</h2>
        <p>
          Checker answers and results are calculated in your browser. The checker does not send
          those answers or results to our waitlist endpoint. Closing or refreshing the checker
          clears its in-memory state.
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">The founding list</h2>
        <p>
          If you choose to join, we collect your email address, your optional role selection, your
          optional product-value selection, and whether you submitted from the home page or checker.
          The server requires affirmative consent before accepting a submission. It adds the
          server-side submission time, the version of the consent notice, a manual retention target,
          and the retention rule to the Telegram message. These metadata are generated by the server,
          not accepted from the browser. Do not include legal or other sensitive personal information;
          the form has no free-text field.
        </p>
        <p>
          The server sends those fields through the Telegram Bot API to a private Telegram chat
          controlled by the site owner. New messages use Telegram&apos;s content-protection option, which
          limits ordinary forwarding and saving in supported Telegram clients; it is not encryption
          and does not enforce deletion. Telegram is a service provider and stores the resulting
          message under its own systems and policies. Authorized access is limited to
          the site owner and Telegram personnel or systems as needed to provide the service.
        </p>
        <p>
          We use the submission for one launch announcement and related administration. We do not
          sell it or share it for advertising. There is no separate waitlist database, but the
          Telegram message remains available until the site owner manually deletes it. Each new
          message carries this administrative rule: delete on verified withdrawal; otherwise within
          30 days after the one launch email; target deletion no later than 365 days after submission.
          The current process has no independently verified automated deletion timer, so the embedded
          date is a manual control rather than a technical guarantee. To request deletion,
          email hello@aipolicyfile.com from the address you submitted. We will delete the accessible
          message when we can verify the request. Telegram or hosting providers may retain limited
          backup, security, or legal records, so we do not promise immediate deletion from every
          system.
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">Contact email</h2>
        <p>
          Messages sent to hello@aipolicyfile.com are routed through Namecheap&apos;s email-forwarding
          service to the owner&apos;s receiving mailbox. The final mailbox provider, its account-side
          retention setting, and its security configuration must be verified in the owner account;
          the website cannot establish those settings from DNS alone. Do not email confidential,
          privileged, or highly sensitive information.
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">Hosting and logs</h2>
        <p>
          Vercel hosts the site and may process standard request data such as IP address, request
          time, route, browser or network information, and operational logs. Our waitlist code does
          not intentionally write submission fields, Telegram messages, or Telegram credentials to
          application logs. Hosting and security records follow Vercel&apos;s configured and contractual
          retention behavior; we do not promise zero retention.
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">Analytics and advertising</h2>
        <p>
          Google Analytics remains blocked unless you select &quot;Allow analytics.&quot; If allowed,
          the site manually sends a page title and path with the URL query string removed. Depending
          on the Google Analytics property&apos;s Enhanced Measurement settings, Google may also collect
          automatic page views, scrolls, outbound-link clicks, file downloads, and form-start or
          form-submit events. An automatic page view, including one triggered by a browser-history
          change, may include the full page location and its query string. Do not put sensitive data
          in a URL.
        </p>
        <p>
          Google Analytics also processes standard analytics data such as session information,
          referrer, browser and device information, language, screen resolution, and approximate
          location. Google says IP addresses are used to derive location before being discarded.
          Site code does not send checker answers, checker results, email addresses, role or
          product-value selections, or other founding-list form-field values to Google Analytics.
          Automatic form events may identify that a form was started or submitted and may include
          form metadata. Advertising storage, ad personalization, and Google Signals are disabled in
          this site&apos;s analytics configuration. The GA4 property&apos;s account-side data-retention and
          Enhanced Measurement settings have not yet been independently verified from this codebase.
        </p>
        <p>
          See Google&apos;s current documentation for its{" "}
          <a
            href="https://support.google.com/analytics/answer/11593727?hl=en"
            target="_blank"
            rel="noopener noreferrer"
            className="text-indigo-700 underline underline-offset-2"
          >
            data collection details
          </a>{" "}
          and{" "}
          <a
            href="https://support.google.com/analytics/answer/11598602?hl=en"
            target="_blank"
            rel="noopener noreferrer"
            className="text-indigo-700 underline underline-offset-2"
          >
            regional processing explanation
          </a>
          , its{" "}
          <a
            href="https://developers.google.com/analytics/devguides/collection/ga4/views?hl=en"
            target="_blank"
            rel="noopener noreferrer"
            className="text-indigo-700 underline underline-offset-2"
          >
            page-view collection guidance
          </a>
          , and its{" "}
          <a
            href="https://support.google.com/analytics/answer/9216061?hl=en"
            target="_blank"
            rel="noopener noreferrer"
            className="text-indigo-700 underline underline-offset-2"
          >
            Enhanced Measurement event list
          </a>
          .
        </p>
        <p>
          Your choice is stored in your browser so it can be honored on later visits. You can change
          it through the persistent Privacy choices button. If you continue without analytics, the
          Google Analytics script is not downloaded.
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">Purposes and legal bases</h2>
        <p>
          Where the EU General Data Protection Regulation applies, founding-list processing and
          optional Google Analytics processing rely on your consent. You may withdraw either choice
          at any time without affecting processing that was lawful before withdrawal. Hosting,
          security, abuse prevention, service diagnostics, and handling privacy or correction
          requests rely on the legitimate interests of keeping the site available, secure, accurate,
          and able to establish or defend legal claims. Data may also be processed when necessary to
          comply with a legal obligation.
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">Recipients and international processing</h2>
        <p>
          Recipient categories are Vercel for hosting and request logs, Telegram for founding-list
          delivery, Google for consented analytics, Namecheap and the receiving mailbox provider for
          contact email, and public authorities when disclosure is legally required. These providers
          may process data in the United States and other countries. The
          applicable provider account, contract, and data-processing terms determine whether an
          adequacy decision, standard contractual clauses, or another transfer mechanism applies.
          Email hello@aipolicyfile.com to request the current provider and safeguard information
          available for your processing.
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">Your privacy rights</h2>
        <p>
          Where applicable, you may request access, correction, deletion, restriction, or portability
          of your personal data, or object to processing based on legitimate interests. You may
          withdraw analytics consent through Privacy choices and may withdraw founding-list consent
          by emailing hello@aipolicyfile.com. You may also lodge a complaint with the data-protection
          supervisory authority where you live or work. We may need information reasonably necessary
          to verify identity and may retain or deny a request where law permits or requires it.
        </p>
        <p>
          Providing founding-list data is optional. If you do not provide an email address and consent,
          you will not receive the launch announcement; the checker remains available. Declining
          analytics does not limit the site. The site does not use the described data for automated
          decisions that produce legal or similarly significant effects.
        </p>
        <p>
          See the official{" "}
          <a
            href="https://eur-lex.europa.eu/eli/reg/2016/679/oj"
            target="_blank"
            rel="noopener noreferrer"
            className="text-indigo-700 underline underline-offset-2"
          >
            GDPR text, including Article 13
          </a>
          .
        </p>

        <h2 className="font-display text-xl font-semibold text-slate-900">Contact</h2>
        <p>
          Privacy questions or deletion requests: hello@aipolicyfile.com. We may need to verify that
          you control the submitted email address before acting on a request.
        </p>
      </div>
    </div>
  );
}
